version: "3.8"
services:
  mongodb:
    image : mongo
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
  nats:
    image: nats
    ports:
      - 4222:4222
    restart: unless-stopped
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_SERVER: mongodb
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      VCAP_APP_HOST: 0.0.0.0
volumes:
  mongodb_data_container: